version: "3.8"

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - server1
      - server2

  server1:
    image: nginx:alpine
    expose:
      - "80"
    volumes:
      - ./server1:/usr/share/nginx/html

  server2:
    image: nginx:alpine
    expose:
      - "80"
    volumes:
      - ./server2:/usr/share/nginx/html
